### ISSUE TITLE
App freezes when 'overwrite empty fields' is not set

### ISSUE THREAD

**Issue by blankey1337** [gilmarsquinelato/i18n-manager#371] opened 2020-04-12 23:04 UTC
I'm a big fan of the app, in fact I just tweeted about it here: https://twitter.com/blankey1337/status/1249462277536800768

![image](https://user-images.githubusercontent.com/42594751/79081991-293e8f00-7cd7-11ea-8a94-66d34c2bf03d.png)

Steps to reproduce:
1. Have a bunch of locale files.
2. Navigate down into a leaf node (a string).
3. Add a From value and one or more To values. 
4. Uncheck 'overwrite not empty fields' .
5. Click Translate

Observe: grey mask overlays the screen, and app has to be closed in order to use it again.

MacOS
Latest version 3.0.0

**Comment by gilmarsquinelato** [comment] 2020-04-14 08:34
Hey @blankey1337, unfortunately I couldn't reproduce this bug =/

I tested with Phoenix wallet files (one of the apps that are using this tool) and it has 1k+ keys and followed your steps, everything was fine.
Can you open the devtools and reproduce again, and after send here a screenshot of it please?

**Comment by otaviobps** [comment] 2020-04-16 21:32
I'm having the same issue. Version 2.0.6 was working fine.

I opened the devtools, but it doesn't show errors.

My steps:
1. Fresh install of 3.0 (had a board failure on my Mac, Apple replaced it and erased my SSD)
2. Opened the directory of the translation files.
3. All keys had all translations, however in some keys there was a yellow circle with a number (missing translation?)
4. Configured the Google API
5. Selected one key (that had all translations, but with yellow circle)
6. Selected to translate all keys but not overwrite.
7. Clicked translate
8. App fade a bit and won't work anymore.

Bellow is the screenshot of it:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28715087/79508611-3d082f00-8010-11ea-9ef9-2afdffe0718e.png">

Inspecting the Network tab, I can see that it doesn't make any API call.

I'm on MacOS 10.15.4 and running version 3.0.0

**Comment by gilmarsquinelato** [comment] 2020-04-17 11:35
@otaviobps related to the warning icon, it's a new indicator to tells how many duplicated values you have, like in your screenshot you have "Todos" in Portuguese and Spanish.

I'm working on that trying to reproduce the bug.

**Comment by gilmarsquinelato** [comment] 2020-04-17 12:10
The fix was released in v3.0.1
Update your apps and check if it's working on your machines please

**Comment by otaviobps** [comment] 2020-04-17 13:08
I can confirm its fixed.

Nice job @gilmarsquinelato it's a really nice app!

**Closed** 2020-04-17 13:20 UTC
Labels: bug
