### ISSUE TITLE
Add validation for item(object) key

### ISSUE THREAD

**Issue by tomma5o** [gilmarsquinelato/i18n-manager#186] opened 2019-08-05 10:18 UTC
It might be interesting add this feature because I suppose this tool is used from non technical people (in my case for example).

And I found some keys like this:
```
{
  "Add_product_:_example": "some text translated",
}
```

How do you think?

**Comment by gilmarsquinelato** [comment] 2019-08-05 10:30
Validations are interesting, but this tool is intended to not restrict the users and to be as most intuitive as possible.
Validation is really tricky because this app supports both `json` and `yaml`, and maybe more in the future, and one restriction may be applied to a type of file and not be applied to others.

I think that in this specific case is a thing of just renaming :)

**Comment by tomma5o** [comment] 2019-08-06 14:18
Ok I imagined that is the only way 😨
So the validation not make sense for you, according to the i18next **_key_** formatting the only symbol used is the _underscore_ but obviously you know better than me all' the edge cases; there are some case in the _.yaml_ file some symbols are used in the syntax?

**Comment by gilmarsquinelato** [comment] 2019-08-06 14:58
The problem is because of this tool is not designed for only one 18n library, it's designed to manage translations, so we can't follow conventions of one or another tool, if we follow that, one time or another we'll have more issues claiming to allow some validations for other library.

**Comment by gilmarsquinelato** [comment] 2019-08-12 09:55
Closing this issue since we will not implement this feature, thanks for the suggestions :D

**Closed by gilmarsquinelato** 2019-08-12 09:55 UTC
